// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
#pragma once

#include "CppSharp.h"
#include <CppSharpTestNative/Consumer.h>

namespace CppSharpTestNative.dll
{
    ref class Base;
    ref class Derived;
}

namespace CppSharpTestNative.dll
{
    public ref class Base : ICppInstance
    {
    public:

        property ::Base* NativePtr;
        property System::IntPtr __Instance
        {
            virtual System::IntPtr get();
            virtual void set(System::IntPtr instance);
        }

        Base(::Base* native);
        static Base^ __CreateInstance(::System::IntPtr native);
        Base();

        Base(CppSharpTestNative.dll::Base^ _0);

        ~Base();

        property int MI
        {
            int get();
            void set(int);
        }

        property double MD
        {
            double get();
            void set(double);
        }

        virtual void DoSomething();

    protected:
        bool __ownsNativeInstance;
    };

    public ref class Derived : CppSharpTestNative.dll::Base
    {
    public:

        Derived(::Derived* native);
        static Derived^ __CreateInstance(::System::IntPtr native);
        Derived();

        Derived(CppSharpTestNative.dll::Derived^ _0);

        ~Derived();

        property System::String^ MS
        {
            System::String^ get();
            void set(System::String^);
        }
    };
}
